var divQuestions;
var nbQstPosees=0,reponse,reponsesCorrectes=0,j,nbQuestions=10;
var numQuestion = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79];
var frag=document.createDocumentFragment();
var time=1200000,mn=20,sec=0;
//tableaux de toutes les questions
var tabQuestions = [ 
[ "Inside local address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "1" ],
[ "Inside global address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "2" ],
[ "Outside local address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "3" ],
[ "Outside global address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "4" ],
[ "Le NAT statique translate : ", "une adresse privée avec une adresse IP publique appartenant à un pool d’adresses.", "plusieurs adresses de diffusion", "une adresse IP publique avec toujours la même adresse IP privée.", "une adresse IP privée avec toujours la même adresse IP public.", "4" ],
[ "Le NAT dynamique translate : ", "une adresse privée avec une adresse IP publique appartenant à un pool d’adresses.", "plusieurs adresses de diffusion", "une adresse IP publique avec toujours la même adresse IP privée.", "une adresse IP privée avec toujours la même adresse IP public.", "1" ],
[ "La plage d’adresses privées de la classe C est : ", "De 192.168.0.0 à 192.168.255.255", "De 10.0.0.0 à 10.255.255.255", "De 224.0.0.0 à 239.255.255.255", "De 172.16.0.0 à 172.31.255.255", "1" ],
[ "La plage d’adresses privées de la classe B est : ", "De 192.168.0.0 à 192.168.255.255", "De 10.0.0.0 à 10.255.255.255", "De 224.0.0.0 à 239.255.255.255", "De 172.16.0.0 à 172.31.255.255", "4" ],
[ "La plage d’adresses privées de la classe A est : ", "De 192.168.0.0 à 192.168.255.255", "De 10.0.0.0 à 10.255.255.255", "De 224.0.0.0 à 239.255.255.255", "De 172.16.0.0 à 172.31.255.255", "2" ],
[ "L'une des étapes suivantes n'est pas une étape de la configuration DHCP : ", "DHCP DISCOVER", "DHCP ARP", "DHCP REQUEST", "DHCP ACK", "2" ],
[ "Le mode de configuration de la commande ip dhcp pool {nom_groupe} est : ", "Globale", "DHCP", "Privilégié", "Interface", "1" ],
[ "Le mode de configuration de la commande default-router {prefix} est : ", "Globale", "DHCP", "Privilégié", "Interface", "2" ],
[ "Le mode de configuration de la commande helper-address {prefix} est : ", "Globale", "DHCP", "Privilégié", "Interface", "4" ],
[ "Le terme PAT signifie : ", "Protocole Address Translation", "Port Address Transmission", "Port Address Translation", "Protocole Address Transmission", "3" ],
[ "La commande qui permet de configurer le PAT sur l'interface Outside est : ", "clear ip nat translation", "access-list {numéro} permit {prefix} {wildcard_mask}", "ip nat outside", "ip nat inside", "1" ],
[ "L'une des commandes suivantes n'est pas une commande de vérification : ", "show ip nat translations", "show ip nat statistics", "debug ip nat", "[no] service dhcp", "4" ],
[ "Le CIDR correspondant à la classe A est : ", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "224.0.0.0/24", "1" ],
[ "Le CIDR correspondant à la classe C est : ", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "224.0.0.0/24", "2" ],
[ "Le CIDR correspondant à la classe B est : ", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "224.0.0.0/24", "3" ],
[ "L'un des services suivants n'est pas un service UDP : ", "ICMP", "TFTP", " NetBIOS", "BOOTP/DHCP", "1" ],
[ "Inside local address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "1" ],
[ "Inside global address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "2" ],
[ "Outside local address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "3" ],
[ "Outside global address est une adresse IP : ", "attribuée à un hôte dans le LAN.", "attribuée par le FAI reconnue par l’Internet pour représenter le LAN.", "d’un hôte du réseau externe telle qu’elle est connue par les utilisateurs du réseau interne. ", "Adresse IP attribuée à un hôte dans le réseau externe.", "4" ],
[ "Le NAT statique translate : ", "une adresse privée avec une adresse IP publique appartenant à un pool d’adresses.", "plusieurs adresses de diffusion", "une adresse IP publique avec toujours la même adresse IP privée.", "une adresse IP privée avec toujours la même adresse IP public.", "4" ],
[ "Le NAT dynamique translate : ", "une adresse privée avec une adresse IP publique appartenant à un pool d’adresses.", "plusieurs adresses de diffusion", "une adresse IP publique avec toujours la même adresse IP privée.", "une adresse IP privée avec toujours la même adresse IP public.", "1" ],
[ "La plage d’adresses privées de la classe C est : ", "De 192.168.0.0 à 192.168.255.255", "De 10.0.0.0 à 10.255.255.255", "De 224.0.0.0 à 239.255.255.255", "De 172.16.0.0 à 172.31.255.255", "1" ],
[ "La plage d’adresses privées de la classe B est : ", "De 192.168.0.0 à 192.168.255.255", "De 10.0.0.0 à 10.255.255.255", "De 224.0.0.0 à 239.255.255.255", "De 172.16.0.0 à 172.31.255.255", "4" ],
[ "La plage d’adresses privées de la classe A est : ", "De 192.168.0.0 à 192.168.255.255", "De 10.0.0.0 à 10.255.255.255", "De 224.0.0.0 à 239.255.255.255", "De 172.16.0.0 à 172.31.255.255", "2" ],
[ "L'une des étapes suivantes n'est pas une étape de la configuration DHCP : ", "DHCP DISCOVER", "DHCP ARP", "DHCP REQUEST", "DHCP ACK", "2" ],
[ "Le mode de configuration de la commande ip dhcp pool {nom_groupe} est : ", "Globale", "DHCP", "Privilégié", "Interface", "1" ],
[ "Le mode de configuration de la commande default-router {prefix} est : ", "Globale", "DHCP", "Privilégié", "Interface", "2" ],
[ "Le mode de configuration de la commande helper-address {prefix} est : ", "Globale", "DHCP", "Privilégié", "Interface", "4" ],
[ "Le terme PAT signifie : ", "Protocole Address Translation", "Port Address Transmission", "Port Address Translation", "Protocole Address Transmission", "3" ],
[ "La commande qui permet de configurer le PAT sur l'interface Outside est : ", "clear ip nat translation", "access-list {numéro} permit {prefix} {wildcard_mask}", "ip nat outside", "ip nat inside", "1" ],
[ "L'une des commandes suivantes n'est pas une commande de vérification : ", "show ip nat translations", "show ip nat statistics", "debug ip nat", "[no] service dhcp", "4" ],
[ "Le CIDR correspondant à la classe A est : ", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "224.0.0.0/24", "1" ],
[ "Le CIDR correspondant à la classe C est : ", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "224.0.0.0/24", "2" ],
[ "Le CIDR correspondant à la classe B est : ", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12", "224.0.0.0/24", "3" ],
[ "L'un des services suivants n'est pas un service UDP : ", "ICMP", "TFTP", " NetBIOS", "BOOTP/DHCP", "1" ],
[ "L'une des caractéristiques de l'adresse unicast est : ", "une adresse physique identifiant une seule carte réseau", "avec cette adresse tous les noeuds du LAN doivent traiter la trame.", "elle permet à un ensemble de noeuds de communiquer entre eux.", "elle crée un bus unique entre la source et la destination.", "1" ],
[ "L'une des caractéristiques de l'adresse de broadcast est : ", "une adresse physique identifiant une seule carte réseau", "avec cette adresse tous les noeuds du LAN doivent traiter la trame.", "elle permet à un ensemble de noeuds de communiquer entre eux.", "elle crée un bus unique entre la source et la destination.", "2" ],
[ "Dans la communication store and forward : ", "Le commutateur attend d’avoir reçu toute la trame avant de la transmettre.", "Le commutateur attend d'avoir reçu les 64 premiers octets avant de commencer à transmettre la trame.", "Pas de vérification d’erreurs.", "Dès que l’adresse de destination est connue, la trame commence à être commutée.", "1" ],
[ "Dans la communication fragment free : ", "Le commutateur attend d’avoir reçu toute la trame avant de la transmettre.", "Le commutateur attend d'avoir reçu les 64 premiers octets avant de commencer à transmettre la trame.", "Pas de vérification d’erreurs.", "Dès que l’adresse de destination est connue, la trame commence à être commutée.", "2" ],
[ "Dans la communication fast forwardd : ", "Le commutateur attend d’avoir reçu toute la trame avant de la transmettre.", "Le commutateur attend d'avoir reçu les 64 premiers octets avant de commencer à transmettre la trame.", "Pas de vérification d’erreurs.", "Dès que l’adresse de destination est connue, la trame commence à être commutée.", "3" ],
[ "Dans la communication cut through : ", "Le commutateur attend d’avoir reçu toute la trame avant de la transmettre.", "Le commutateur attend d'avoir reçu les 64 premiers octets avant de commencer à transmettre la trame.", "Pas de vérification d’erreurs.", "Dès que l’adresse de destination est connue, la trame commence à être commutée.", "4" ],
[ "Lorsque le voyant système d'un commutateur est éteint, alors : ", "le système est hors tension", "le système est sous-tension", "y a un problème suite au POST", "l'alimentation de sécurité est utilisée", "1" ],
[ "Lorsque le voyant système d'un commutateur est éteint, alors : ", "le système est hors tension", "le système est sous-tension", "y a un problème suite au POST", "l'alimentation de sécurité est utilisée", "2" ],
[ "Lorsque le voyant système d'un commutateur est éteint, alors : ", "le système est hors tension", "le système est sous-tension", "y a un problème suite au POST", "l'alimentation de sécurité est utilisée", "3" ],
[ "Lorsque le voyant RPS d'un commutateur est éteint, alors : ", "le système est hors tension", "le système est sous-tension", "y a un problème suite au POST", "l'alimentation de sécurité est utilisée", "4" ],
[ "La comande enable permet de : ", "accéder au mode privilégié", "accéder au mode de configuration globale", "afficher le fichier de configuration actif", "passer dans le mode configuration de l'interface", "1" ],
[ "La comande configure terminal permet de : ", "accéder au mode privilégié", "accéder au mode de configuration globale", "afficher le fichier de configuration actif", "passer dans le mode configuration de l'interface", "2" ],
[ "La comande show running-config permet de : ", "accéder au mode privilégié", "accéder au mode de configuration globale", "afficher le fichier de configuration actif", "passer dans le mode configuration de l'interface", "3" ],
[ "La comande interface [type] [numéro/sous numéro] permet de : ", "accéder au mode privilégié", "accéder au mode de configuration globale", "afficher le fichier de configuration actif", "passer dans le mode configuration de l'interface", "4" ],
[ "Dans l'état de transmission, le port : ", "émet et reçoit les trames", "écoute les BPDU pour s'assurer qu'il n'y ait pas de boucle.", "écoute les BPDU pour découvrir les adresses MAC.", "ne peut ni émettre ni recevoir les trames", "1" ],
[ "Dans l'état d'ecoute, le port : ", "émet et reçoit les trames", "écoute les BPDU pour s'assurer qu'il n'y ait pas de boucle.", "écoute les BPDU pour découvrir les adresses MAC.", "ne peut ni émettre ni recevoir les trames", "2" ],
[ "Dans l'état d'apprentissage, le port : ", "émet et reçoit les trames", "écoute les BPDU pour s'assurer qu'il n'y ait pas de boucle.", "écoute les BPDU pour découvrir les adresses MAC.", "ne peut ni émettre ni recevoir les trames", "3" ],
[ "Dans l'état de blocage, le port : ", "émet et reçoit les trames", "écoute les BPDU pour s'assurer qu'il n'y ait pas de boucle.", "écoute les BPDU pour découvrir les adresses MAC.", "ne peut ni émettre ni recevoir les trames", "4" ],
[ "La deuxième étape de VLSM consiste à : ", "agréger les différents instances d’un niveau ", "identifier le besoin", "connaître le nombre d’utilisateurs pour chaque sous-réseau", "Déterminer la classe d’adresse ou l’agrégat d’adresses", "3" ],
[ "La troisième étape de VLSM consiste à : ", "agréger les différents instances d’un niveau ", "identifier le besoin", "connaître le nombre d’utilisateurs pour chaque sous-réseau", "Déterminer la classe d’adresse ou l’agrégat d’adresses", "4" ],
[ "Le port auxiliaire port auxiliaire de routeur Cisco permet un : ", "Accès de base pour configuration", "Accès pour configuration au travers d’une ligne analogique et modems interposés.", "Accès pour connection internet", "Accès pour maintenance", "1" ],
[ "L'interface LAN de routeur Cisco permet un : ", "Accès de base pour configuration", "Accès pour configuration au travers d’une ligne analogique et modems interposés.", "Accès pour connection internet", "Accès pour maintenance", "2" ],
[ "La ligne VTY permet un : ", "Accès primaire", "Accès à distance", "Accès via un client Telnet", "Accès utilisant le serveur HTTP", "3" ],
[ "La ligne console permet un : ", "Accès primaire", "Accès à distance", "Accès via un client Telnet", "Accès utilisant le serveur HTTP", "1" ],
[ "La Ligne auxiliaire permet un : ", "Accès primaire", "Accès à distance", "Accès via un client Telnet", "Accès utilisant le serveur HTTP", "2" ],
[ "L'explorateur Web permet un : ", "Accès primaire", "Accès à distance", "Accès via un client Telnet", "Accès utilisant le serveur HTTP", "4" ],
[ "Pour arrêter l’exécution d’une commande, il faut utiliser une des combinaisons de touches suivantes :", "CTRL+Z", "CTRL+ALT+6", "ALT+TAB", "CTRL+MAJ+6", "4" ],
[ "L'affichage qui designe le mode utilisateur est  ", "Router #", "Router >", "Router (config) #", "Router (config-if) #", "1" ],
[ "L'affichage qui designe le mode privilégié est  ", "Router #", "Router >", "Router (config) #", "Router (config-if) #", "2" ],
[ "L'affichage qui designe le mode configuration globale est  ", "Router #", "Router >", "Router (config) #", "Router (config-if) #", "3" ],
[ "L'affichage qui designe le mode interface est  ", "Router #", "Router >", "Router (config) #", "Router (config-if) #", "4" ],
[ "ID de dispositif : ", "Nom d’hôte et nom de domaine du voisin", "Une adresse pour chaque protocole routé du voisin", "Interface du voisin utilisée pour se connecter au routeur local", "Fonction du dispositif voisin (routeur, pont, commutateur, etc.)", "1" ],
[ "Liste d’adresses : ", "Nom d’hôte et nom de domaine du voisin", "Une adresse pour chaque protocole routé du voisin", "Interface du voisin utilisée pour se connecter au routeur local", "Fonction du dispositif voisin (routeur, pont, commutateur, etc.)", "2" ],
[ "Identifiant de port : ", "Nom d’hôte et nom de domaine du voisin", "Une adresse pour chaque protocole routé du voisin", "Interface du voisin utilisée pour se connecter au routeur local", "Fonction du dispositif voisin (routeur, pont, commutateur, etc.)", "3" ],
[ "Liste de capacités : ", "Nom d’hôte et nom de domaine du voisin", "Une adresse pour chaque protocole routé du voisin", "Interface du voisin utilisée pour se connecter au routeur local", "Fonction du dispositif voisin (routeur, pont, commutateur, etc.)", "4" ],
[ "La commande show cdp permet d'afficher : ", "les compteurs de temps pour CDP", "les interfaces sur lesquelles CDP est activé", "les informations d’un ou des voisins", "la liste des voisins CDP ainsi que les informations les concernant", "1" ],
[ "La commande show cdp interface [{type} {numéro}] permet d'afficher : ", "les compteurs de temps pour CDP", "les interfaces sur lesquelles CDP est activé", "les informations d’un ou des voisins", "la liste des voisins CDP ainsi que les informations les concernant", "2" ],
[ "La commande show cdp entry {nom | *} permet d'afficher : ", "les compteurs de temps pour CDP", "les interfaces sur lesquelles CDP est activé", "les informations d’un ou des voisins", "la liste des voisins CDP ainsi que les informations les concernant", "3" ],
[ "La commande show cdp neighbors [detail] permet d'afficher : ", "les compteurs de temps pour CDP", "les interfaces sur lesquelles CDP est activé", "les informations d’un ou des voisins", "la liste des voisins CDP ainsi que les informations les concernant", "4" ],
[ "La couche internet de modèle TCP/IP permet : ", "La sélection du chemin", "L'assurance de la qualité de transmission", "La transmession des données", "Le codage des données", "1" ],
];

window.addEventListener("load", poserQuestion, false);


